# Stubs for django.contrib.gis.gdal (Python 3.5)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from django.contrib.gis.gdal.error import GDALException as GDALException, OGRException as OGRException, OGRIndexError as OGRIndexError, SRSException as SRSException, check_err as check_err
from django.contrib.gis.gdal.geomtype import OGRGeomType as OGRGeomType
from django.contrib.gis.gdal.envelope import Envelope as Envelope

HAS_GDAL = ...  # type: bool
